xpath_moreInfo = "//span[text()='More Information']"
xpath_buyNow = "//span[text()='Buy Now']"
xpath_price = "//*[@id='__next']/div[3]/div/div[2]/div[1]/div[1]/h4"
xpath_rating = "//*[@id='__next']/div[3]/div/div[2]/div[1]/div[2]/span/span[1]/span"
xpath_productDetails = "//*[@id='__next']/div[3]/div/div[2]/div[3]"
xpath_phoneNumber = "//*[@id='__next']/div[4]/div/div[2]/div/div/div[2]/input"
xpath_continueBtn = "//button"
xpath_continueBtnLogin = "//span[text()='Continue']"
xpath_continue = "//*[@id='__next']/div[4]/div/div[2]/div/button/div/span"
xpath_continueBtn_address = "//*[@id='__next]/div[4]/div/div[2]/div/button"
xpath_continueBtn_payment = "//span[text()='Continue']"
xpath_placeOrder = "//span[text()='Place order']"
xpath_selectDeliveryAddress = "//span[text()='Select Delivery Address']"
xpath_deliverToThisAddress_ = "//button[text()='Deliver to this Address']"
xpath_addressPaymentPage = "/html/body/div[1]/div/div[2]/div[2]/div/div/div[1]/div[2]/div/div/div[2]/div[3]/span"
